apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: chandrucyril/hello-app:latest
        ports:
        - containerPort: 3000

        env:
        - name: APP_ENV
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: APP_ENV
        - name: APP_NAME
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: APP_NAME

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
